apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-userlist-pv
  labels:
    pv: mongodb-userlist-pv
spec:
  storageClassName: ""
  accessModes:
    - "ReadWriteMany"
  capacity:
    storage: "100Mi"
  nfs:
    path: /var/nfs/kubedata
    server: 35.158.254.170
  