apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mongo-user-data
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/kubedata
    server: 35.158.254.170
