apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mongo-user-data
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/mongodb-pvc
    server: 35.158.254.170
