apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  destination:
    name: in-cluster
    namespace: applications
  project: default
  source:
    repoURL: https://github.com/hakobmkoyan771/infra.git
<<<<<<< HEAD
    path: .
=======
    path: Applications
>>>>>>> fb4383d8174cbaa469bb483eb5d78c1c11a438c9
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
