apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts
  template:
    metadata:
      labels:
        app: contacts
    spec:
      containers:
        - name: contacts
          image: hakobmkoyan771/contactpython:0.1.0
          ports:
            - name: contactsport
              containerPort: 80
          env:
            - name: MONGO_DB_IP_ADDRESS
              value: mongosvc.applications.svc.cluster.local
          readinessProbe:
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 15
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 5
