apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: nginxhttp
      nodePort: 31313
  selector:
    app: nginx
