apiVersion: v1
kind: Service
metadata:
  name: ui-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: identiui-http
      protocol: "TCP"
      nodePort: 30003
  selector:
    app: identidock-ui
