apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-userlist-pvc
spec:
  storageClassName: "nfs-client"
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "100Mi"