apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6IlpHVjJiM0J6ZEdGemEyRmpjakU2UTBKTkt6QTNjVkI2YlZGRmJXUjRTa3hxTVd0TFNFdHJZa0pQVWpSTmRGVT0ifX19
kind: Secret
metadata:
  name: webapps-reg-secret
type: kubernetes.io/dockerconfigjson
